title: The Sy Schiff Art Archive
email: hello@syschiff.art
description: >-
  The digital home of the art of Sy Schiff
baseurl: ""
url: "https://syschiff.art"

page_gen-dirs: true
page_gen:
- data: all_images
  template: image
  dir: img
  name: title
- data: multi_images
  template: multi_image
  dir: img
  name: title

google_analytics: G-WRJYZ2JTRD
  
# Build settings
plugins:
  - jekyll-datapage-generator
  - jekyll-seo-tag

# Exclude from processing.
exclude:
  - README.md
  - scripts/
  - .tmp/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
